using System;
using System.Collections.Generic;
using System.Linq;

namespace ManiaNet.Manialink.ManiaScript
{
    public abstract class ManiascriptCode
    {
        /// <summary>
        /// The actual Maniascript Code
        /// </summary>
        public string Code { get; private set; }

        /// <summary>
        /// Code will be surrounded with an autogenerated Void function if true.
        /// </summary>
        public bool Inline { get; private set; }

        /// <summary>
        /// The priority to order it in the respective section
        /// </summary>
        public int Priority { get; private set; }

        /// <summary>
        /// Create a block manialink code
        /// </summary>
        /// <param name="code">The ManiaScript code</param>
        /// <param name="priority">Sets a priority to order it in the respective section</param>
        /// <param name="inline">Surround code with an autogenerated Void function?</param>
        public ManiascriptCode(string code, int priority = 5, bool inline = true)
        {
            this.Code = code;
            this.Priority = priority;
            this.Inline = inline;
        }
    }

    internal class ManiascriptFunction : ManiascriptCode
    {
        public ManiascriptFunction(string code, int priority) :
            base(code, priority, true)
        { }
    }

    internal class ManiascriptGlobal : ManiascriptCode
    {
        public ManiascriptGlobal(string code, int priority = 5)
            : base(code, priority, true)
        { }
    }

    internal class ManiascriptMain : ManiascriptCode
    {
        public ManiascriptMain(string code, int priority = 5, bool inline = true)
            : base(code, priority, inline)
        { }
    }
}